name: Build Quarkus Image
on:
  pull_request:
  push:
    branches:
      - main
env:
  IMAGE_NAME: jlink-quarkus-test-image
  TAGS: v1 ${{ github.sha }}
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ inputs.checkout-repo }}
        ref: ${{ inputs.checkout-ref }}
        submodules: true
        fetch-depth: 0
    - name: Setup and Build Quarkus
      id: build_image_quarkus
      uses: redhat-actions/s2i-build@v2
      with:
        path_context: 'quarkus-quickstart/getting-started'
        # TODO: Need Jmods image
        builder_image: 'registry.access.redhat.com/ubi9/openjdk-17'
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.TAGS }}
