name: Build and Push Quarkus Image to Quay
on:
  push:
    branches:
      - main
env:
  LANG: en_US.UTF-8
  IMAGE: ubi9-openjdk-17
jobs:
  call-build:
    uses: ./.github/workflows/build-quarkus.yml
    with:
      image: ubi9-openjdk-17
  push-image:
    - name: Push To Quay Action
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image_spring.outputs.image }}
        tags: ${{ steps.build_image_spring.outputs.tags }}
        registry: quay.io/jmatsuok/jlink-tests
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
